// Eleanor's content
window.SITE_DATA = {
  name: "Eleanor Lansner",
  tagline: ["Brand storytelling", "consumer truth", "commercial impact."],
  hero: {
    eyebrow: "Product Marketer · MS Business Analytics '26",
    headline: ["Stories that ", "{em:move}", " product."],
    lede: "Product marketer with 4+ years translating consumer insight and brand strategy into go-to-market plans that ship. Now deepening the analytical foundation underneath the storytelling.",
  },
  meta: [
    { k: "Based in", v: "New York City, NY" },
    { k: "Available", v: "Summer 2026" },
    { k: "Focused on", v: "Sport, lifestyle, consumer brands" },
    { k: "Reach me", v: "eleanor.lansner@gmail.com" },
  ],
  about: [
    "I'm a product marketer who fell for the craft at the intersection of data, consumer behavior, and commercial outcome. Four years at Trustpilot and experience at early-stage start-ups taught me how to take a product from ideation to launch, with six-plus seasonal launches shipped, positioning frameworks grounded in segmentation data, and sales enablement that actually closes pipeline.",
    "Now finishing an MS in Business Analytics at CU Boulder because the best product stories I've ever written were rooted in real behavioral data, and I want to widen that lane. ML, segmentation, performance modeling.",
    "Off the clock you'll find me on a trail, a wall, or a flight somewhere new. I'm a runner, a climber, and a lifelong adventure lover, the same instincts I bring to a launch plan. ",
  ],
  now: {
    location: "New York, NY",
    items: [
      { k: "Reading", v: "Running with the Buffaloes" },
      { k: "Just graduated", v: "MSc Business Analytics, CU Boulder" },
      { k: "Training for", v: "Chicago Marathon" },
      { k: "Building", v: "4 The Girls Jog Club NYC" },
      { k: "Listening", v: "How I Built This" },
      { k: "Next trip", v: "Dolomites, March 2027" },
    ],
  },
  marquee: [
    "Go-to-market", "Consumer segmentation", "Product storytelling", "Seasonal launches",
    "Behavioral analytics", "Cross-functional", "Brand strategy", "Performance KPIs",
  ],
  career: [
    {
      when: "Sep 2025 – Feb 2026",
      role: "Product Strategy & Analytics Intern",
      company: "Auddia Inc · Boulder, CO",
      summary: "Discovery, dashboards, and roadmap shaping for a consumer audio product.",
      detail: [
        "Led strategic discovery of new product features by conducting user and market research, translating consumer insights into a structured roadmap that aligned cross-functional teams around high-impact opportunities.",
        "Built and maintained dashboards in Looker and Google Analytics to monitor product KPIs, track feature adoption, and surface performance insights that informed go-to-market planning.",
      ],
    },
    {
      when: "Aug 2021 – Jun 2025",
      role: "Product Marketing Manager",
      company: "Trustpilot · New York, NY",
      summary: "Owned six seasonal launches; built positioning frameworks that lifted product appeal {stat:+7%} and supported {stat:$211M+} in annual revenue.",
      detail: [
        "Drove end-to-end go-to-market execution for six seasonal product launches, aligning Design, Product, Sales, and Marketing to ensure deliverables met strategic objectives and launch milestones were hit on time.",
        "Developed segment-specific consumer messaging and positioning frameworks grounded in market research and behavioral data, improving overall product appeal by {stat:7%}.",
        "Conducted market research and competitive analysis to uncover new opportunities and inform portfolio planning, supporting prioritization decisions that contributed to {stat:$211M+} in annual revenue.",
        "Monitored product performance KPIs and lifecycle campaign metrics, analyzing patterns in consumer behavior and conversion data to optimize go-to-market plans.",
        "Built and maintained sales enablement content (pitch decks, battlecards, use-case guides), embedding customer evidence into deal cycles and outbound to accelerate pipeline.",
      ],
    },
    {
      when: "promoted from",
      role: "Associate Product Marketing Manager",
      company: "Trustpilot",
      summary: "Managed launch timelines and cross-functional alignment across Design, Development, and Marketing.",
      detail: [
        "Managed product launch timelines and cross-functional dependencies, ensuring teams followed agreed development and go-to-market calendars.",
        "Established strong working relationships across Design, Development, and Marketing teams, providing input on concept relevance and ensuring alignment on product storytelling and launch plans.",
      ],
    },
    {
      when: "started as",
      role: "Customer Marketing Coordinator",
      company: "Trustpilot",
      summary: "Behaviorally driven lifecycle campaigns that lifted engagement and adoption {stat:+11%}.",
      detail: [
        "Executed behaviorally driven lifecycle campaigns across consumer segments, increasing engagement and product adoption by {stat:11%}.",
        "Maintained accurate campaign data and product content across systems, ensuring downstream accuracy for go-to-market execution and sales readiness milestones.",
      ],
    },
    {
      when: "Apr 2021 – Aug 2021",
      role: "Marketing Specialist",
      company: "CYBRI · New York, NY",
      summary: "Translated technical capabilities into consumer-facing product stories.",
      detail: [
        "Developed consumer-facing positioning and content for a technical product, translating complex capabilities into clear product stories that resonated across multiple channels.",
        "Conducted competitive research and consumer flow audits to identify market patterns and sharpen positioning, improving conversion across the buyer journey.",
      ],
    },
  ],
  projects: [
    {
      tag: "Consumer Segmentation",
      status: "Case study",
      title: "Vail Resorts: clustering the skier",
      blurb: "Applied statistical clustering to behavioral data to develop core consumer segments, then translated findings into segment-specific marketing recommendations targeting purchase growth across key consumer occasions.",
      tools: ["R", "Clustering", "Behavioral data", "GTM strategy"],
      viz: "segments",
      brand: "Vail Resorts",
    },
    {
      tag: "B2B Market Segmentation",
      status: "Case study",
      title: "EverCommerce: finding the white space",
      blurb: "R-based clustering on B2B customer data to identify high-growth segments, sharpening cross-sell strategy and tightening go-to-market focus for a multi-product portfolio.",
      tools: ["R", "Segmentation", "B2B GTM", "Cross-sell"],
      viz: "bars",
      brand: "EverCommerce",
    },
    {
      tag: "GTM Playbook",
      status: "Trustpilot",
      title: "Six seasonal launches, one rhythm",
      blurb: "Built a repeatable launch framework spanning Design through Sales (calendars, deliverable specs, positioning frameworks, sales enablement) that scaled with the team and held milestones on time.",
      tools: ["Launch ops", "Positioning", "Sales enablement", "Cross-functional"],
      viz: "calendar",
      brand: "Trustpilot",
    },
    {
      tag: "Consumer Insight",
      status: "Trustpilot",
      title: "Segment-led messaging frameworks",
      blurb: "Built consumer messaging architectures grounded in behavioral data and qualitative research, lifting overall product appeal by 7% and giving Sales a sharper story for every audience.",
      tools: ["Behavioral analytics", "Messaging", "Positioning"],
      viz: "wave",
      brand: "Trustpilot",
    },
    {
      tag: "Financial Modeling",
      status: "Case study",
      title: "Amazon: scaling mixed reality training",
      blurb: "Built financial models and ROI simulations in R to evaluate the scalability of mixed reality for global warehouse training. Delivered a data-backed no-go recommendation grounded in cost-benefit analysis, market research, and technical feasibility.",
      tools: ["R", "Financial modeling", "ROI simulation", "Feasibility analysis"],
      viz: "bars",
      brand: "Amazon",
    },
    {
      tag: "Health Analytics",
      status: "Case study",
      title: "Sleep patterns & chronic health risk",
      blurb: "Cleaned data and ran multi-logistic regressions in R to study the relationship between sleep patterns and chronic health risks. Surfaced significant correlations between sleep hygiene and incidence of hypertension and obesity.",
      tools: ["R", "Logistic regression", "Data cleaning", "Public health data"],
      viz: "wave",
      brand: "Sleep Study",
    },
    {
      tag: "Marketing Automation",
      status: "Brock USA",
      title: "Lifecycle email automation",
      blurb: "Designed and shipped a lifecycle email automation program for Brock USA, mapping triggers to buyer-journey stages so sales got warmer leads and customers got the right message at the right moment.",
      tools: ["Lifecycle marketing", "Automation", "Segmentation", "Copywriting"],
      viz: "calendar",
      brand: "Brock USA",
    },
  ],
  education: [
    {
      when: "2026",
      degree: "MSc, Business Analytics",
      school: "Leeds School of Business · CU Boulder",
      focus: "ML, AI, advanced data modeling applied to consumer segmentation, behavioral analytics, and product performance optimization.",
    },
    {
      when: "2019",
      degree: "BA, Economics",
      school: "King's College London",
      focus: "Foundations in micro/macro, behavioral economics, and quantitative methods.",
    },
  ],
  skills: {
    "Product marketing": ["GTM Strategy", "Seasonal Launch Execution", "Product Storytelling", "Positioning", "Sales Enablement", "Omnichannel"],
    "Insight & analytics": ["Consumer Segmentation", "Market Research", "Trend Analysis", "Behavioral Analytics", "KPI Monitoring"],
    "Tools": ["Looker", "Google Analytics", "Amplitude", "Python", "R", "SQL", "Figma"],
  },
  contact: [
    { ch: "Email", v: "eleanor.lansner@gmail.com", href: "mailto:eleanor.lansner@gmail.com" },
    { ch: "LinkedIn", v: "linkedin.com/in/eleanor-lansner", href: "https://linkedin.com/in/eleanor-lansner" },
    { ch: "Phone", v: "(917) 498-9731", href: "tel:+19174989731" },
    { ch: "Location", v: "Boulder, CO", href: null },
  ],
};
